Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  config.vm.define "alaalalmS" do |server|
    server.vm.hostname = "alaalalmS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider :libvirt do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
