Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider :libvirt do |lv|
    lv.memory = 2048
    lv.cpus = 2
  end

  config.vm.define "alaalalmS" do |server|
    server.vm.hostname = "alaalalmS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "alaalalmSW" do |worker|
    worker.vm.hostname = "alaalalmSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
