Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Server
  config.vm.define "alaalalmS" do |server|
    server.vm.hostname = "alaalalmS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # Worker
  config.vm.define "alaalalmSW" do |worker|
    worker.vm.hostname = "alaalalmSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end